import { createIcons, Plus, Search, RefreshCw, Download, ExternalLink, ArrowLeft, X, Check, FileCheck, LockKeyhole, Trash2, Pencil, Copy, Save } from 'lucide';
import { assess, blindScreen, BLIND_MINIMUMS, nextStatuses, statuses } from './domain.js';
const icons={Plus,Search,RefreshCw,Download,ExternalLink,ArrowLeft,X,Check,FileCheck,LockKeyhole,Trash2,Pencil,Copy,Save};
const $=s=>document.querySelector(s),app=$('#app'),dialog=$('#dialog');
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const icon=n=>`<i data-lucide="${n}"></i>`;
const button=(label,action,ic='',cls='')=>`<button type="button" data-action="${action}" class="${cls}">${ic?icon(ic):''}${esc(label)}</button>`;
const badge=s=>`<span class="pill ${s}">${esc(s.replaceAll('_',' '))}</span>`;
const money=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(n);
const date=s=>s?(/^\d{4}-\d{2}-\d{2}$/.test(s)?new Date(s+'T12:00:00').toLocaleDateString():new Date(s).toLocaleString()):'';
let state={profile:null,jobs:[]},detailTab='evidence',search='',filter='',results=[],noticeTimer;
function toast(message){$('#notice').textContent=message;$('#notice').hidden=false;clearTimeout(noticeTimer);noticeTimer=setTimeout(()=>$('#notice').hidden=true,7000);}
function decorate(){createIcons({icons});}
async function api(path,method='GET',data){const r=await fetch('/api'+path,{method,headers:method==='GET'?{}:{'Content-Type':'application/json'},body:data?JSON.stringify(data):undefined});const out=await r.json();if(!r.ok)throw new Error(out.error||'Request failed.');return out;}
async function load(){state=await api('/state');render();}
function currentJob(){return state.jobs.find(j=>j.id===location.hash.split('/')[1]);}
function replaceJob(job){state.jobs=state.jobs.map(j=>j.id===job.id?job:j);render();}
function route(){return location.hash.startsWith('#job/')?'job':location.hash==='#profile'?'profile':'queue';}
function render(){document.querySelectorAll('[data-view]').forEach(a=>a.setAttribute('aria-current',a.dataset.view===(route()==='job'?'queue':route())?'page':'false'));if(route()==='profile')profileView();else if(route()==='job'&&currentJob())jobView(currentJob());else queueView();decorateBlindScreen();decorate();}
function queueView(){const pending=state.jobs.filter(j=>['review_ready','approved','preparing'].includes(j.status)).length;
 const active=state.jobs.filter(j=>['submitted','interview'].includes(j.status)).length;
 const today=new Date().toLocaleDateString('en-CA'),due=state.jobs.filter(j=>j.followup&&j.followup<=today&&!['rejected','withdrawn','skipped','expired'].includes(j.status)).length;
 app.innerHTML=`<div class="heading"><div><h1>Applications</h1><p>Above ${money(state.profile.targetTC)} annual compensation target <span aria-hidden="true"> &middot; </span> ${state.profile.weeklyHours} preparation hours / week</p></div><div class="actions">${button('Find jobs','discover','search')}${button('Add role','add','plus','primary')}</div></div>
 <div class="stats"><div><strong>${state.jobs.length}</strong><span>Saved roles</span></div><div><strong>${pending}</strong><span>Review & preparation</span></div><div><strong>${active}</strong><span>Submitted & interviewing</span></div><div><strong>${due}</strong><span>Follow-ups due</span></div></div>
 <div class="toolbar"><input id="search" aria-label="Search saved roles" placeholder="Search company, role or location" value="${esc(search)}"><select id="filter" aria-label="Filter by status"><option value="">All statuses</option>${statuses.map(s=>`<option value="${s}" ${s===filter?'selected':''}>${s.replaceAll('_',' ')}</option>`).join('')}</select>${button('','reload','refresh-cw','icon')}${button('Export tracker','csv','download')}</div><div id="jobRows"></div>
 <div class="doc-links"><a href="/companion.zip" download>Download Chrome autofill companion</a><span class="muted">No applications are submitted automatically.</span></div>`;
 app.querySelector('[data-action=reload]').title='Refresh applications';renderRows();}
function renderRows(){const rows=state.jobs.filter(j=>(!filter||j.status===filter)&&`${j.company} ${j.title} ${j.location}`.toLowerCase().includes(search.toLowerCase()));
 $('#jobRows').innerHTML=rows.length?`<div class="table-wrap"><table><thead><tr><th>Role</th><th>Location</th><th>Annual TC</th><th>Status</th><th>Next follow-up</th></tr></thead><tbody>${rows.map(j=>`<tr><td><button class="role-link" data-job="${j.id}">${esc(j.title)}</button><span class="small">${esc(j.company)}</span></td><td>${esc(j.location||'Unknown')}<br><span class="small">${esc(j.workMode||'Schedule unknown')}</span></td><td>${j.tcMin!==null||j.tcMax!==null?`${j.tcMin!==null?money(j.tcMin):'?'} - ${j.tcMax!==null?money(j.tcMax):'?'}`:'Unknown'}<br><span class="small">${esc(assess(j,state.profile).pay)}</span></td><td>${badge(j.status)}${j.approval&&j.approval.profileRevision!==state.profile.revision?'<p class="small due">Approval needs review</p>':''}</td><td>${esc(j.followup||'Not set')}</td></tr>`).join('')}</tbody></table></div>`:'<div class="empty"><h2>No matching roles</h2><p>Add a role or search an employer job board.</p></div>';renderBlindColumn();}
function jobView(job){const match=assess(job,state.profile);
 app.innerHTML=`${button('All applications','back','arrow-left','back')}<div class="heading"><div><p>${esc(job.company)}</p><h1>${esc(job.title)}</h1><p>${esc(job.location||'Location unknown')} &middot; ${esc(job.workMode||'Schedule unknown')}</p></div><div class="actions">${badge(job.status)}${button('Edit role','edit','pencil')}<a href="${esc(job.url)}" target="_blank" rel="noopener noreferrer">Official posting ${icon('external-link')}</a></div></div>
 <div class="tabs" role="tablist" aria-label="Application details">${[['evidence','Evidence & fit'],['draft','Application draft'],['activity','Follow-up & activity']].map(([id,label])=>`<button role="tab" aria-selected="${detailTab===id}" data-tab="${id}">${label}</button>`).join('')}</div><div id="detail"></div>`;
 if(detailTab==='evidence') $('#detail').innerHTML=`<div class="split"><section><h2>Target evidence</h2><p class="small">${esc(job.source||'User-provided posting')}${job.sourceCheckedAt?' | Checked '+esc(date(job.sourceCheckedAt)):''}</p><div class="source-text">${esc(job.description||'No description added.')}</div>${job.requirements?`<h3 class="spaced">Selected requirements</h3><div class="source-text">${esc(job.requirements)}</div>`:''}</section><section><h2>Inferences</h2><p class="muted">${esc(match.inference)}</p>${match.evidence.length?match.evidence.map(e=>`<div class="evidence-row"><div><h3>${esc(e.label)}</h3><p class="small">${e.factIds.length?`${e.factIds.length} relevant fact${e.factIds.length>1?'s':''} found`:'No confirmed evidence found'}</p></div><span class="pill ${e.factIds.length?'approved':'blocked'}">${e.factIds.length?'Possible relevance':'Unknown'}</span></div>`).join(''):'<p class="muted">No tracked topics matched this description.</p>'}<h2>Unknowns</h2><ul>${match.unknowns.map(u=>`<li>${esc(u)}</li>`).join('')}</ul><h2>Compensation evidence</h2><p>${esc(match.pay)}</p><p class="muted">${esc(job.payEvidence||'No compensation source recorded. A base-salary range is not an annual total-compensation offer.')}</p>${button('Prepare evidence draft','draft-tab','file-check','primary')}</section></div>`;
 if(detailTab==='draft'){draftView(job,match);answerView(job);}
 if(detailTab==='activity'){ $('#detail').innerHTML=`<div class="split"><section><h2>Follow-up</h2><form id="followupForm"><div class="form-grid"><label>Next follow-up<input type="date" name="followup" value="${esc(job.followup)}"></label><label class="full">Notes<textarea name="notes" rows="5">${esc(job.notes)}</textarea></label></div><button class="primary spaced" type="submit">${icon('save')}Save follow-up</button></form><h2>Status</h2><div class="status-actions">${nextStatuses(job.status).filter(s=>s!=='approved'&&s!=='submitted').map(s=>`<button data-transition="${s}">${esc(s.replaceAll('_',' '))}</button>`).join('')}</div>${['approved','preparing'].includes(job.status)?button('Record submission','record','check','spaced'):''}${job.submittedAt?`<h3 class="spaced">Submission recorded</h3><p>${esc(date(job.submittedAt))}</p><p class="muted">${esc(job.receipt)}</p>`:''}</section><section><h2>Activity</h2><div id="events">Loading activity...</div></section></div>`;api(`/jobs/${job.id}/events`).then(rows=>{if($('#events'))$('#events').innerHTML=rows.map(e=>`<div class="event"><time>${esc(date(e.timestamp))}</time><span>${esc(e.action.replaceAll('_',' '))}</span></div>`).join('');}).catch(e=>toast(e.message));}
}
function draftView(job,match){const suggested=new Set(job.draft?.factIds||match.evidence.flatMap(e=>e.factIds));
 const stale=job.draft&&job.draftProfileRevision!==state.profile.revision;
 const approved=['approved','preparing'].includes(job.status)&&job.approval?.profileRevision===state.profile.revision;
 const closed=['submitted','interview','offer','rejected','withdrawn','expired','skipped'].includes(job.status);
 $('#detail').innerHTML=`<div class="split wide"><section><h2>Candidate facts</h2><form id="draftForm">${state.profile.facts.filter(f=>f.confirmed&&f.usable).map(f=>`<div class="fact"><input type="checkbox" name="factIds" id="fact-${esc(f.id)}" value="${esc(f.id)}" ${suggested.has(f.id)?'checked':''} ${closed?'disabled':''}><label for="fact-${esc(f.id)}">${esc(f.claim)}<span class="small">${esc(f.source)}</span></label></div>`).join('')||'<p class="empty">No confirmed application evidence. Add facts in Profile & evidence.</p>'}<button type="submit" class="primary spaced" ${closed?'disabled':''}>${icon('file-check')}Generate evidence draft</button></form><p class="muted">Unconfirmed and application-excluded facts are not available for drafts.</p></section><section><h2>Application draft</h2>${stale?'<p class="notice">Your profile changed. Regenerate this draft and review it again.</p>':''}${job.draft?`<div class="actions">${button('Resume text','resume','download')}${button('Letter','letter','download')}</div><pre class="pre">${esc(job.draft.resume)}</pre><details><summary>Cover letter</summary><pre class="pre">${esc(job.draft.letter)}</pre></details><details><summary>Source references</summary>${job.draft.citations.map(c=>`<p class="small">${esc(c.factId)}: ${esc(c.source)}</p>`).join('')}</details>
 ${!closed&&!approved?`<form id="reviewForm" class="checklist"><h3>Review</h3><label class="check"><input name="facts" type="checkbox" required>I confirm these experience claims and their sources.</label><label class="check"><input name="constraints" type="checkbox" required>I reviewed pay, location and Blind rating unknowns and choose to proceed.</label><label class="check"><input name="contents" type="checkbox" required>I reviewed the draft and contact details for this role.</label><button type="submit" class="primary" ${stale?'disabled':''}>${icon('check')}Approve preparation</button></form>`:''}
 ${approved?`<div class="checklist"><p>${badge('approved')} Current profile and draft reviewed</p><div class="actions">${button('Autofill packet','packet','download','primary')}${button('Record submission','record','check')}</div><p class="muted">Final submission, attachments, custom answers and consent remain on the employer website.</p></div>`:''}`:'<p class="empty">No draft prepared for this role.</p>'}</section></div>`;}
function field(label,name,value='',type='text',extra=''){return `<label>${esc(label)}<input type="${type}" name="${name}" value="${esc(value??'')}" ${extra}></label>`;}
function answerView(job){if(!job.draft)return;const editable=['review_ready','approved','preparing'].includes(job.status);$('#detail').insertAdjacentHTML('beforeend',`<section class="field-block spaced"><h2>Application answers</h2>${(job.answers||[]).map(answer=>`<details><summary>${esc(answer.question)}</summary><pre class="pre">${esc(answer.text)}</pre><p class="small">${answer.citations.map(c=>esc(c.source)).join(' | ')}</p></details>`).join('')}${(job.answers||[]).length?button('Export answer drafts','answers','download','spaced'):''}${editable?`<form id="answerForm" class="spaced"><label>Application question<textarea name="question" required maxlength="2000" rows="2"></textarea></label><h3 class="spaced">Supporting candidate facts</h3>${job.draft.citations.map(c=>`<label class="check"><input type="checkbox" name="factIds" value="${esc(c.factId)}">${esc(c.claim)}</label>`).join('')}<button type="submit">${icon('file-check')}Draft from selected facts</button></form>`:''}</section>`);}
function profileView(){const p=state.profile;
 app.innerHTML=`<div class="heading"><div><h1>Profile & evidence</h1><p>Candidate facts are separate from target requirements and inferences.</p></div></div><div class="profile-width"><form id="profileForm"><h2>Application contact details</h2><div class="form-grid">${field('Full name','name',p.name)}${field('Email','email',p.email,'email')}${field('First name','firstName',p.firstName)}${field('Last name','lastName',p.lastName)}${field('Phone','phone',p.phone,'tel')}${field('LinkedIn','linkedin',p.linkedin,'url')}${field('Website','website',p.website,'url')}</div><h2>Future role constraints</h2><div class="form-grid">${field('Annual TC target (USD, excluding sign-on)','targetTC',p.targetTC,'number','min="0" max="10000000" required')}${field('Preparation hours per week','weeklyHours',p.weeklyHours,'number','min="1" max="168" required')}${field('Acceptable locations','locations',p.locations)}<label>Maximum office days<select name="officeDays"><option value="">Not confirmed</option>${[0,1,2,3,4,5].map(n=>`<option value="${n}" ${p.officeDays===n?'selected':''}>${n===0?'Remote only':n+' days'}</option>`).join('')}</select></label></div><button class="primary spaced" type="submit">${icon('save')}Save profile</button></form><div class="spread spaced"><h2>Candidate facts</h2>${button('Add fact','add-fact','plus')}</div>${p.facts.map(f=>`<div class="fact"><div style="flex:1;min-width:0"><p>${esc(f.claim)}</p><p class="small">${esc(f.source)}</p><div class="actions"><span class="pill ${f.confirmed?'approved':'blocked'}">${f.confirmed?'Confirmed':'Needs confirmation'}</span><span class="small">${f.usable?'Available for applications':'Excluded from applications'}</span></div></div><button class="icon" title="Edit fact" aria-label="Edit fact" data-fact="${esc(f.id)}">${icon('pencil')}</button></div>`).join('')}</div>`;
}
function openDialog(html){dialog.innerHTML=html;addBlindFields();dialog.showModal();decorate();}
function blindBadge(job){const b=blindScreen(job);return `<span class="pill blind-${b.status}">${esc(b.label)}</span>`;}
function renderBlindColumn(){
 const table=$('#jobRows table');if(!table)return;
 table.querySelector('thead tr').insertAdjacentHTML('beforeend','<th>Blind screen</th>');
 for(const row of table.querySelectorAll('tbody tr')){
   const job=state.jobs.find(j=>j.id===row.querySelector('[data-job]').dataset.job);
   row.insertAdjacentHTML('beforeend',`<td>${blindBadge(job)}<p class="small">WLB ${job.blindWorkLifeBalance??'?'} / Overall ${job.blindOverall??'?'}</p></td>`);
 }
}
function blindRuleText(){return `Blind work-life balance at least ${BLIND_MINIMUMS.workLifeBalance.toFixed(1)}; overall at least ${BLIND_MINIMUMS.overall.toFixed(1)}. Either rating below its minimum means no, regardless of pay. Missing ratings remain unknown.`;}
function decorateBlindScreen(){
 if(route()==='profile'){
   $('#profileForm').insertAdjacentHTML('afterend',`<section class="field-block spaced"><h2>Blind minimums</h2><p>${blindRuleText()}</p><p class="small">User-defined decision rules, separate from candidate experience and employer evidence.</p></section>`);return;
 }
 if(route()!=='job'||!currentJob())return;
 const job=currentJob(),b=blindScreen(job);
 app.querySelector('.tabs').insertAdjacentHTML('beforebegin',`<section class="blind-rubric field-block"><div class="spread"><h2>Blind screen</h2>${blindBadge(job)}</div><div class="blind-metrics">${b.metrics.map(m=>`<div><strong>${m.value===null?'Unknown':(Number.isInteger(m.value)?m.value.toFixed(1):String(m.value))}</strong><span>${esc(m.label)} / minimum ${m.minimum.toFixed(1)}</span></div>`).join('')}</div><p class="${b.status==='no'?'due':'muted'}">${esc(b.reasons.join(' ')|| (b.status==='pass'?'Both minimums met. This is not an overall role recommendation.':'Ratings still need checking. This is not a pass.'))}</p><p class="small">${job.blindSourceUrl?`<a href="${esc(job.blindSourceUrl)}" target="_blank" rel="noopener noreferrer">Blind source</a>`:'Source unknown'}${job.blindCheckedDate?' | Checked '+esc(date(job.blindCheckedDate)):''}. Company-level ratings do not establish conditions on a specific team.</p></section>`);
 if(b.status==='no'){
   const approve=$('#reviewForm button[type=submit]');if(approve){approve.disabled=true;approve.title='This role fails your Blind minimums.';}
   for(const action of app.querySelectorAll('[data-action=packet],[data-transition=preparing]')){action.disabled=true;action.title='This role fails your Blind minimums.';}
 }
}
function addBlindFields(){
 const form=dialog.querySelector('#jobForm');if(!form)return;
 const job=state.jobs.find(j=>j.id===form.dataset.id)||{};
 form.querySelector('.foot').insertAdjacentHTML('beforebegin',`<section class="field-block spaced"><h3>Blind ratings</h3><p class="small">${blindRuleText()}</p><div class="form-grid">${field('Blind work-life balance','blindWorkLifeBalance',job.blindWorkLifeBalance,'number','min="1" max="5" step="any"')}${field('Blind overall rating','blindOverall',job.blindOverall,'number','min="1" max="5" step="any"')}${field('Blind rating source URL','blindSourceUrl',job.blindSourceUrl,'url')}${field('Blind check date','blindCheckedDate',job.blindCheckedDate,'date',`max="${new Date().toISOString().slice(0,10)}"`)}</div></section>`);
}
const modalHeader=title=>`<div class="dialog-head"><h2>${esc(title)}</h2><button type="button" class="icon" data-close title="Close" aria-label="Close">${icon('x')}</button></div>`;
function jobDialog(job={}){openDialog(`${modalHeader(job.id?'Edit role':'Add role')}<form id="jobForm" data-id="${job.id||''}"><div class="form-grid">${field('Company','company',job.company,'text','required maxlength="2000"')}${field('Role title','title',job.title,'text','required maxlength="2000"')}<label class="full">Official job URL<input name="url" type="url" value="${esc(job.url)}" required></label>${field('Location','location',job.location)}${field('Office schedule','workMode',job.workMode)}<label class="full">Job description<textarea name="description" rows="7" maxlength="60000">${esc(job.description)}</textarea></label><label class="full">Selected target requirements<textarea name="requirements" rows="3" maxlength="12000">${esc(job.requirements)}</textarea></label>${field('Annual total compensation minimum (USD)','tcMin',job.tcMin,'number','min="0"')}${field('Annual total compensation maximum (USD)','tcMax',job.tcMax,'number','min="0"')}<label class="full">Pay source or recruiter quote<textarea name="payEvidence" rows="2" maxlength="2000">${esc(job.payEvidence)}</textarea></label><p class="small full">Leave total compensation blank when only a base salary range is available.</p></div><div class="foot"><button type="button" data-close>Cancel</button><button type="submit" class="primary">Save role</button></div></form>`);}
function discoverDialog(){results=[];openDialog(`${modalHeader('Find jobs')}<form id="discoverForm"><div class="form-grid"><label>Job board<select name="provider"><option value="greenhouse">Greenhouse</option><option value="lever">Lever</option><option value="ashby">Ashby</option></select></label>${field('Company board slug','board','mongodb','text','required pattern="[a-zA-Z0-9_-]{1,80}"')}${field('Role keywords','query','software')}${field('Location keywords','location','')}</div><button class="primary spaced" type="submit">${icon('search')}Search employer feed</button></form><div id="results"></div>`);}
function factDialog(f={}){openDialog(`${modalHeader(f.id?'Edit candidate fact':'Add candidate fact')}<form id="factForm" data-id="${esc(f.id||'')}"><label>Experience claim<textarea name="claim" rows="5" required maxlength="5000">${esc(f.claim)}</textarea></label><label class="spaced">Source<input name="source" value="${esc(f.source)}" required maxlength="1000"></label><label class="check"><input type="checkbox" name="confirmed" ${f.confirmed?'checked':''}>I confirm this claim is accurate.</label><label class="check"><input type="checkbox" name="usable" ${f.usable?'checked':''}>Include as available application evidence.</label><div class="foot">${f.id?button('Delete fact','delete-fact','trash-2','danger'):''}<button type="submit" class="primary">Save fact</button></div></form>`);}
function download(text,name,type='text/plain'){const url=URL.createObjectURL(new Blob([text],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),5000);}
async function saveProfile(p){state.profile=await api('/profile','PUT',p);render();toast('Profile saved. Existing approvals require a fresh review.');}
app.addEventListener('input',e=>{if(e.target.id==='search'){search=e.target.value;renderRows();}});
app.addEventListener('change',e=>{if(e.target.id==='filter'){filter=e.target.value;renderRows();}});
document.addEventListener('click',async e=>{const close=e.target.closest('[data-close]');if(close){dialog.close();return;}const jobLink=e.target.closest('[data-job]');if(jobLink){detailTab='evidence';location.hash='job/'+jobLink.dataset.job;return;}const fact=e.target.closest('[data-fact]');if(fact){factDialog(state.profile.facts.find(f=>f.id===fact.dataset.fact));return;}const tab=e.target.closest('[data-tab]');if(tab){detailTab=tab.dataset.tab;render();return;}
 const target=e.target.closest('[data-action],[data-transition],[data-import]');if(!target)return;target.disabled=true;
 try{const action=target.dataset.action,job=currentJob();
 if(target.dataset.transition){replaceJob(await api(`/jobs/${job.id}/transition`,'POST',{revision:job.revision,status:target.dataset.transition}));toast('Status updated.');}
 else if(target.dataset.import!==undefined){const out=await api('/jobs','POST',results[Number(target.dataset.import)]);if(!state.jobs.some(j=>j.id===out.job.id))state.jobs.unshift(out.job);target.textContent=out.duplicate?'Already saved':'Saved';target.dataset.import='';delete target.dataset.import;render();return;}
 else if(action==='add')jobDialog();else if(action==='edit')jobDialog(job);else if(action==='discover')discoverDialog();else if(action==='back')location.hash='queue';else if(action==='reload')await load();else if(action==='csv')window.location.assign('/api/export');else if(action==='draft-tab'){detailTab='draft';render();}else if(action==='add-fact')factDialog();
 else if(action==='delete-fact'){const id=$('#factForm').dataset.id;await saveProfile({...state.profile,facts:state.profile.facts.filter(f=>f.id!==id)});dialog.close();}
 else if(action==='resume'||action==='letter')download(action==='resume'?job.draft.resume:job.draft.letter,action==='resume'?'resume-draft.txt':'cover-letter-draft.txt');
 else if(action==='answers')download(job.answers.map(a=>a.question+'\n\n'+a.text).join('\n\n---\n\n'),'application-answer-drafts.txt');
 else if(action==='packet'){const p=await api(`/jobs/${job.id}/packet`);download(JSON.stringify(p,null,2),'application-packet.json','application/json');toast('Packet downloaded. It expires in 24 hours.');}
 else if(action==='record')openDialog(`${modalHeader('Record a submission')}<form id="submissionForm"><p>${esc(job.company)}: ${esc(job.title)}</p><label>Confirmation message or receipt reference<textarea name="receipt" required maxlength="2000"></textarea></label><label class="check"><input name="confirmed" type="checkbox" required>I submitted this application on the employer website.</label><div class="foot"><button type="submit" class="primary">Record submission</button></div></form>`);
 }catch(error){toast(error.message);}finally{target.disabled=false;decorate();}
});
document.addEventListener('submit',async e=>{if(!e.target.matches('#jobForm,#discoverForm,#profileForm,#factForm,#draftForm,#reviewForm,#followupForm,#submissionForm,#answerForm'))return;e.preventDefault();const form=e.target,submit=e.submitter,values=Object.fromEntries(new FormData(form)),job=currentJob();if(submit)submit.disabled=true;
 try{
 if(form.id==='jobForm'){const existing=state.jobs.find(j=>j.id===form.dataset.id);const data={...existing,...values};if(existing)replaceJob(await api(`/jobs/${existing.id}`,'PUT',data));else{const out=await api('/jobs','POST',data);if(!state.jobs.some(j=>j.id===out.job.id))state.jobs.unshift(out.job);detailTab='evidence';location.hash='job/'+out.job.id;}dialog.close();render();toast('Role saved.');}
 if(form.id==='discoverForm'){const out=await api('/discover','POST',values);results=out.jobs;$('#results').innerHTML=`<h3 class="spaced">${out.total} matching roles${out.truncated?' (first 100 shown)':''}</h3><p class="small">Checked ${esc(date(out.checkedAt))}</p>${results.map((r,i)=>`<div class="result"><div><h3>${esc(r.title)}</h3><p>${esc(r.company)} &middot; ${esc(r.location)}</p><a href="${esc(r.url)}" target="_blank" rel="noopener noreferrer">Official posting</a></div><button data-import="${i}">${icon('plus')}Save role</button></div>`).join('')||'<p class="empty">No roles match these filters.</p>'}`;decorate();}
 if(form.id==='profileForm')await saveProfile({...state.profile,...values,officeDays:values.officeDays===''?null:Number(values.officeDays)});
 if(form.id==='factForm'){const id=form.dataset.id||crypto.randomUUID(),fact={...values,id,confirmed:values.confirmed==='on',usable:values.usable==='on'};await saveProfile({...state.profile,facts:[...state.profile.facts.filter(f=>f.id!==id),fact]});dialog.close();}
 if(form.id==='draftForm'){replaceJob(await api(`/jobs/${job.id}/draft`,'POST',{revision:job.revision,factIds:new FormData(form).getAll('factIds')}));toast('Draft generated from selected facts only.');}
 if(form.id==='answerForm'){replaceJob(await api(`/jobs/${job.id}/answer`,'POST',{revision:job.revision,question:values.question,factIds:new FormData(form).getAll('factIds')}));toast('Answer draft saved. Review again before exporting an autofill packet.');}
 if(form.id==='reviewForm'){replaceJob(await api(`/jobs/${job.id}/transition`,'POST',{revision:job.revision,status:'approved',review:{facts:values.facts==='on',constraints:values.constraints==='on',contents:values.contents==='on'}}));toast('Preparation approved. Nothing has been submitted.');}
 if(form.id==='followupForm'){replaceJob(await api(`/jobs/${job.id}`,'PUT',{...job,...values}));toast('Follow-up saved.');}
 if(form.id==='submissionForm'){replaceJob(await api(`/jobs/${job.id}/transition`,'POST',{revision:job.revision,status:'submitted',confirmed:values.confirmed==='on',receipt:values.receipt}));dialog.close();toast('Your submission was recorded.');}
 }catch(error){toast(error.message);}finally{if(submit)submit.disabled=false;}
});
window.addEventListener('hashchange',()=>{render();window.scrollTo({top:0,behavior:'instant'});});
load().catch(e=>{app.innerHTML=`<div class="empty"><h1>Workspace unavailable</h1><p>${esc(e.message)}</p>${button('Try again','reload','refresh-cw')}</div>`;decorate();});
